### ISSUE TITLE
Getting an error "rand.Seed has been deprecated" on random-numbers

### ISSUE THREAD

**Issue by onattech** [gosamples-dev/samples#2]
Could you please update https://gosamples.dev/random-numbers/.
As of 1.20, getting this error
`rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: Programs that call Seed and then expect a specific sequence of results from the global random source (using functions such as Int) can be broken when a dependency changes how much it consumes from the global random source. To avoid such breakages, programs that need a specific result sequence should use NewRand(NewSource(seed)) to obtain a random generator that other packages cannot access.  (SA1019)`

**Comment by gosamplesdev** [comment]
Thank you, I've updated the blog post: https://gosamples.dev/random-numbers/
